---
- name: install common utilities
  hosts: all
  become: true

  tasks:
    - name: install common
      community.general.pkgng:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmux
        - htop

- name: configure ipfw
  hosts: all
  become: true
  roles:
    - ipfw

- name: install fail2ban
  hosts: all
  become: true
  roles:
    - fail2ban

- name: weekly reboot
  hosts: all
  become: true
  roles:
    - reboot
