---
- name: install common utilities
  hosts: all
  become: true

  tasks:
    - name: install common
      community.general.pkgng:
        name: "{{ item }}"
        state: latest
      with_items:
        - tmux
        - htop

- name: configure ipfw
  hosts: all
  become: true
  roles:
    - ipfw

- name: fail2ban for ssh
  hosts: all
  become: true
  roles:
    - fail2ban_ssh

- name: fail2ban for shadowsocks
  hosts: gcp_label_shadowsocks_service_yes
  become: true
  roles:
    - fail2ban_shadowsocks

- name: weekly reboot
  hosts: all
  become: true
  roles:
    - reboot

- name: time sync
  hosts: all
  become: true
  roles:
    - time_sync
