---
- name: Configure custom ipfw rules
  ansible.builtin.copy:
    src: ipfw.rules
    dest: /usr/local/etc/ipfw.rules
    owner: root
    group: wheel
    mode: "0755"

- name: Enable ipfw on boot
  community.general.sysrc:
    name: firewall_enable
    value: "YES"

- name: Set ipfw type as open
  community.general.sysrc:
    name: firewall_type
    value: open

- name: Enable custom ipfw rules
  community.general.sysrc:
    name: firewall_script
    value: "/usr/local/etc/ipfw.rules"

- name: Restart ipfw
  ansible.builtin.service:
    name: ipfw
    state: restarted
