---
- name: install dependencies
  community.general.pkgng:
    name: py37-fail2ban
    state: latest

- name: configure fail2ban ipfw-table action
  ansible.builtin.copy:
    src: ipfw-table.local
    dest: /usr/local/etc/fail2ban/action.d/ipfw-table.local
    owner: root
    group: wheel
    mode: "0644"

- name: configure shadowsocks filter
  ansible.builtin.copy:
    src: shadowsocks-libev.conf
    dest: /usr/local/etc/fail2ban/filter.d/shadowsocks-libev.conf
    owner: root
    group: wheel
    mode: "0644"

- name: configure sshd jail
  ansible.builtin.copy:
    src: sshd.local
    dest: /usr/local/etc/fail2ban/jail.d/sshd.local
    owner: root
    group: wheel
    mode: "0644"

- name: configure shadowsocks jail
  ansible.builtin.copy:
    src: shadowsocks-libev.local
    dest: /usr/local/etc/fail2ban/jail.d/shadowsocks-libev.local
    owner: root
    group: wheel
    mode: "0644"

- name: enable fail2ban on boot
  community.general.sysrc:
    name: fail2ban_enable
    value: "YES"

- name: restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: configure newsyslog
  ansible.builtin.copy:
    src: newsyslog.conf
    dest: /etc/newsyslog.conf.d/fail2ban.conf
    owner: root
    group: wheel
    mode: "0644"
