---
- name: Install ntp.conf
  ansible.builtin.copy:
    src: ntp.conf
    dest: /etc/ntp.conf
    owner: root
    group: wheel
    mode: "0544"

# https://cromwell-intl.com/open-source/google-freebsd-tls/freebsd.html
- name: Fix clock drift
  ansible.posix.sysctl:
    name: kern.timecounter.hardware
    value: ACPI-fast
    state: present

- name: Enable ntpdate on boot
  community.general.sysrc:
    name: google_clock_skew_daemon_enable
    value: "NO"
